services:
    order-service:
        image: hnrkjnsn/order-service:1.0.0
        environment:
            - ASPNETCORE_URLS=http://+:8080
        expose:
        - "8080"

    nginx:
        image: nginx:latest
        volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
        - order-service
        ports:
        - "4000:4000"