name: Byg et Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker_image_pipeline:
    name: Build Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    env:
      IMAGE_NAME: order-service
      FULL_IMAGE_NAME: ${{secrets.DOCKER_USER}}/${{env.IMAGE_NAME}}

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_TOKEN}}

      - name: Get metadata from csproj-file
        uses: kzrnm/get-net-sdk-project-versions-action@v2
        id: get-version
        with:
          proj-path: OrderServiceAPI/OrderServiceAPI.csproj
    
      - name: Build and push the Docker image with version from csproj file
        run: |
          docker build . -f OrderServiceAPI/Dockerfile -t $VERSIONED_IMAGE_NAME
          docker push $VERSIONED_IMAGE_NAME
        env:
          VERSIONED_IMAGE_NAME: ${{env.FULL_IMAGE_NAME}}:${{steps.get-version.outputs.informational-version}}

      - name: Tag image as latest and push to Docker Hub
        run: |
          docker tag ${{env.FULL_IMAGE_NAME}}:${{steps.get-version.outputs.informational-version}} ${LASTEST_IMAGE_NAME}
          docker push ${LATEST_IMAGE_NAME}
        env:
          LASTEST_IMAGE_NAME: ${{env.FULL_IMAGE_NAME}}:latest
